define(function(require, exports, module) {
'use strict'

module.exports = require('multiline')(function() {/*

Lorizzle ipsum sit check it out, consectetuer adipiscing elit. Nullizzle sapien velizzle, my shizz volutpizzle, suscipit quis, gravida vel, arcu. Shut the shizzle up mah nizzle tortor. Sed phat. yo dolor dapibus turpis tempizzle fo shizzle my nizzle. Maurizzle break it down dawg izzle turpizzle. Get down get down in mofo. Boofron rhoncizzle nisi. Phat hac mofo platea dictumst. Shizznit nizzle. Shiz tellizzle sure, pretizzle you son of a bizzle, mattizzle gangsta, eleifend vitae, nunc. Ma nizzle suscipit. Integizzle sempizzle velit sizzle cool.

Sizzle yo tortor get down get down arcu boom shackalack consequizzle. Check it out convallizzle, arcu izzle ghetto posuere, doggy lorizzle fo shizzle my nizzle pede, get down get down ghetto augue dolizzle sed velizzle. Mammasay mammasa mamma oo sa ac diam nizzle elit varizzle tincidunt. Curabitizzle uhuh ... yih! nisi, go to hizzle izzle, rizzle eleifend, tincidunt shit, metizzle. Nunc shizzle my nizzle crocodizzle neque. Uhuh ... yih! dope dolizzle sheezy amet, consectetizzle gizzle dawg. Maecenas izzle boofron. In break yo neck, yall. Vestibulum shiz erizzle fo shizzle ma nizzle aliquet dictizzle. In facilisizzle check out this sizzle amet nibh. Cras shiznit. Sure eu check it out izzle ma nizzle lacinia shizzlin dizzle. Sure nizzle massa dope urna crazy lobortis. Black shizzle my nizzle crocodizzle est, bibendum pulvinar, ornare i'm in the shizzle, imperdizzle shizzle my nizzle crocodizzle, lacizzle. Fo egizzle dope boofron massa adipiscing pizzle. Curabitur izzle nisl quis tellizzle ornare pizzle.

Vestibulum ante boofron primizzle yo mamma doggy gizzle uhuh ... yih! et ultrices yippiyo hizzle Dope; Sizzle shiznit nulla quis brizzle ornare pot. Shiznit euismod izzle. Praesent black accumsizzle fo shizzle. Praesent stuff dui, adipiscing vitae, gravida crunk, fizzle vitae, ante. Yo malesuada bibendum funky fresh. Sed in shiz et augue hizzle laorizzle. Crazy sed shut the shizzle up. Check it out shiznit. Praesent eu lacus quizzle lacizzle own yo' adipiscing. Donec tellus we gonna chung pimpin' tincidunt mollizzle. Integer you son of a bizzle. Nizzle nizzle. Quisque magna ghetto, shiz vitae, yo mamma ac, gizzle egestizzle, dawg. Integer owned pimpin' lectus. Etizzle sollicitudin tristique that's the shizzle. Phasellizzle mi erizzle, convallizzle izzle, brizzle vel, the bizzle that's the shizzle, i saw beyonces tizzles and my pizzle went crizzle. Fusce doggy maurizzle, crunk eu, dang eu, i saw beyonces tizzles and my pizzle went crizzle a, lectus. Fo shizzle maurizzle crunk, yo molestie, adipiscing break yo neck, yall, fo shizzle sizzle amizzle, enizzle.

In gravida ligula nec fo shizzle. Prizzle for sure. That's the shizzle shizzlin dizzle. Donec in mi a erizzle gizzle. Bizzle vizzle ipsizzle. Sizzle nizzle i'm in the shizzle gangsta lacus. Pizzle pimpin' ipsum vitae tellivizzle euismizzle break it down. Integer gizzle risus. My shizz lobortizzle yo vizzle felis. Morbi check it out justo. Break it down eu pot fo magna elementizzle bling bling. Morbi yo mamma, arcu shiz euismizzle porta, gangsta crunk adipiscing nunc, i'm in the shizzle ornare mi ma nizzle sizzle fo shizzle mah nizzle fo rizzle, mah home g-dizzle est. Morbi turpizzle. Vestibulum ante break yo neck, yall fo shizzle izzle faucibus shit luctizzle get down get down ultricizzle posuere cubilia Curae; Vestibulizzle vehicula, justo laoreet tincidunt we gonna chung, risizzle lorem gravida gizzle, a fermentum urna metus shiznit nibh. Dizzle pretizzle erizzle yo mamma nulla. Phasellus black. Cizzle socizzle shiz penatibizzle et dizzle parturient montes, shiz ridiculizzle that's the shizzle. Prizzle izzle da bomb fringilla i'm in the shizzle ultricizzle congue. Donizzle tellivizzle mi.

Away egizzle sizzle. Nullizzle sit ghetto dizzle bizzle massa tincidunt funky fresh. In et erat. Vivamizzle lectizzle pot, lacinia go to hizzle amizzle, vulputate vitae, my shizz izzle, nunc. Crizzle mofo amet mauris. Nullizzle fermentum pot nunc. Morbi my shizz, elizzle izzle i saw beyonces tizzles and my pizzle went crizzle, velizzle owned dizzle justo, own yo' condimentizzle yippiyo purus quizzle ghetto. Pimpin' owned mammasay mammasa mamma oo sa fizzle. Mofo daahng dawg. In hac habitasse fo shizzle dictumst. Get down get down sizzle amet dui. Its fo rizzle sizzle bow wow wow. Gizzle yo risus. Shizznit ma nizzle, hizzle egizzle adipiscing suscipizzle, owned izzle pretium lorizzle, quizzle fermentizzle my shizz elizzle in risus.

Praesent dignissim fo quizzle fo shizzle molestie shizzle my nizzle crocodizzle. Sizzle bow wow wow mi, dapibizzle da bomb, bow wow wow izzle, break it down doggy, its fo rizzle. Owned check out this. Boofron sure. Morbi nulla erizzle, luctus sed, gangsta nizzle, bibendum you son of a bizzle, dolizzle. Dizzle get down get down izzle. Shiznit vel tortor. Shut the shizzle up dope nibh. Vestibulum i saw beyonces tizzles and my pizzle went crizzle. Donizzle dignissizzle sapien vel arcu. Bizzle a sizzle vel sem eleifend eleifend. Fusce pulvinar, bling bling nizzle vestibulizzle fringilla, nizzle libero tempor erizzle, vehicula elementizzle augue sizzle pot pede. Quisque vestibulizzle hizzle dolor. erizzle volutpat. Ghetto sagittis, shizzlin dizzle tellivizzle ultricies consequat, massa lacus gravida go to hizzle, crackalackin sagittis enizzle fo shizzle sizzle yo mamma.

*/})
})
